Added Connect Wallet Button to Flash Card
kernel-community/kernel-v2 pull request #257
Opened 2022-02-15 05:51 UTC by Malayvasa

## Summary of changes
Added Connect Wallet Button Inside Flashcard Component

## Relevant Context
- https://github.com/kernel-community/kernel-v2/issues/235

## Screenshots (if appropriate):
<img width="399" alt="Screenshot 2022-02-15 at 11 14 02 AM" src="https://user-images.githubusercontent.com/22751053/153999848-2b6e4d19-867a-49e2-8d4f-2be0917c24ee.png">

## Types of changes

- [ ] Content edit, File upload, content addition
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Technical Documentation Update
- [ ] Other (please describe):

## Does this introduce a breaking change?

_Breaking change is defined as_ **"A fix or feature that would cause existing functionality to change."**

- [ ] Yes
- [x] No

2022-02-15 13:47 UTC, andytudhope requested changes

2022-02-15 13:47 UTC, andytudhope commented on src/modules/flashcard/card.js
> +              //onClick={revealCallback}
Let's just remove, rather than commenting out and leaving dead code around the place in the course of implementing this.

2022-02-15 13:47 UTC, andytudhope commented on src/modules/flashcard/card.js
> +    fetchEns: false
Let's set this to `true` - I was just simplifying things when we were testing.

2022-02-15 13:47 UTC, andytudhope commented on src/modules/flashcard/card.js
> +                sx={{position: 'absolute', zIndex: 10}}>
I'm not sure that switching z-index from `10` to `-1` is the best approach here. @angelagilhotra do you have any thoughts about how this could be made more robust, or is it good enough in your book?

2022-02-17 14:39 UTC, andytudhope approved these changes

2022-02-18 02:48 UTC, probablyangg commented on src/modules/flashcard/card.js
> +                      {data.connectors.map((x) => (
Do we want to do this? Or should we just stick with Metamask?

2022-02-18 02:50 UTC, angelagilhotra commented on src/modules/flashcard/card.js
> +                      {data.connectors.map((x) => (
if we want, then we should also add a key in here just for react's sanity
```
data.connectors.map((x,k) => {... (use key to identify all the mapped divs) })
```

2022-02-18 02:53 UTC, angelagilhotra commented
let's also remove infura id from [here](https://github.com/kernel-community/kernel-v2/blob/22f69d55d8845e6860e416a1fe1543d138fa8d05/gatsby-browser.js#L13)?

2022-02-18 02:55 UTC, angelagilhotra commented on src/modules/flashcard/card.js
> +    {data: accountData, error: accountError, loading},
i think we can remove these, since we're not using them anyway?

2022-02-18 02:59 UTC, probablyangg commented on src/modules/flashcard/card.js
> +                      {data.connectors.map((x) => (
I'd suggest keeping a simple util file, that exports connectors[0] object

```
// util.js

export const connectors = () => [
  new InjectedConnector({ chains }),
  new WalletConnectConnector({
    chains,
    options: {
      infuraId,
      qrcode: true,
    },
  }),
];

export enum Connector {
  "INJECTED",
  "WALLETCONNECT",
} 

```

And then, when calling for metamask, we just do:

```
connect(connectors[Connector.INJECTED])
```

2022-02-18 02:59 UTC, angelagilhotra commented on src/modules/flashcard/card.js
> +                      {data.connectors.map((x) => (
but if this feels overkill, feel free to ignore 😅

2022-02-18 03:02 UTC, probablyangg commented on src/modules/flashcard/card.js
> +    {data: accountData, error: accountError, loading},
let's also remove this, since it's not being used anyway?

2022-02-18 13:13 UTC, andytudhope commented on src/modules/flashcard/card.js
> +    {data: accountData, error: accountError, loading},
keep `accountData` in as we will need it for he next stage.

2022-03-03 13:58 UTC, merged