Kernel Fang UI translation stuff
kernel-community/kernel-v2 pull request #263
Opened 2022-02-15 22:24 UTC by fangningc

Beginning Spanish translation for my adventure [<notion link>](https://www.notion.so/gitcoin/Fang-Ning-Chen-Chen-829073745d724801ad8841a45e80638e)

2022-02-16 12:17 UTC, gjacuna requested changes

2022-02-16 12:17 UTC, gjacuna commented on content/es/UI.json
> +    "Page_Language_Selector": "Selector de idioma de la página",
Pondría solo "Selector de Idioma". Creo que "de la página" es redundante.

2022-02-16 12:17 UTC, gjacuna commented on content/es/UI.json
> +      "governance": "Gobernancia",
Esto debiera ser "Gobernanza", que supuestamente es el término oficial.

2022-02-16 12:17 UTC, gjacuna commented on content/es/UI.json
> +      "Community_Blog": "Blog de la communidad Kernel",
Le sacaría "Kernel", también me parece redundante.

2022-02-16 12:17 UTC, gjacuna commented on content/es/UI.json
> +      "Guide": "Guia",
Guía (falta el tilde)

2022-02-16 12:17 UTC, gjacuna commented on content/es/UI.json
> +      "Code": "Código",
En Code, Caution, Cogitate y Conceal tengo mis dudas. Todos los demás verbos están en forma imperativa, y estos en infinitivo. Debiéramos dejarlos todos igual, imperativo que es más como una invitación. "Programa" o "Codea" que no es oficial, pero se usa; "Medita", "Oculta", etc

2022-02-16 12:17 UTC, gjacuna commented on content/es/UI.json
> +      "About": "Sobre",
Personalmente me gusta más "Acerca de", creo que se entiende mejor

2022-02-17 10:22 UTC, fangningc commented on content/es/UI.json
> +    "Page_Language_Selector": "Selector de idioma de la página",
Si, de acuerdo! Creo que al principio lo traduje a "Selector de idioma", pero luego vi que también hay un "Blog_Language_Selector" en linea 53, entonces por eso incluí este detalle.

2022-02-18 11:33 UTC, andytudhope approved these changes

2022-02-18 11:35 UTC, merged