module 0, money language and conversation
kernel-community/kernel-v2 pull request #317
Opened 2022-04-06 11:25 UTC by fangningc

2022-04-07 12:35 UTC, miguel567 requested changes
Done. Very good translations, some minor changes!

2022-04-07 12:35 UTC, miguel567 commented on content/es/learn/module-0/conversation.mdx
> +> "La humanidad moderna no aprende siendo dotada. Nuestro camino es otro. Estamos constituidos para hacer preguntas. Para nosotros, conocer es algo que se logra con esfuerzo, con libre albedrío. La t
AS-IS: "La tarea del ser humano moderno buscar y encontrar conocimiento de forma clara y definitiva."

TO-BE: "La tarea del ser humano moderno es buscar y encontrar conocimiento de forma clara y definitiva."

2022-04-07 12:35 UTC, miguel567 commented on content/es/learn/module-0/conversation.mdx
> +> "La humanidad moderna no aprende siendo dotada. Nuestro camino es otro. Estamos constituidos para hacer preguntas. Para nosotros, conocer es algo que se logra con esfuerzo, con libre albedrío. La t
AS-IS: "Difícil yardas."

Here I'm not sure if we should translate literally as yards is a word not normally used in Spanish. I would translate it is "Long road":

TO-BE: "Un largo camino."

2022-04-07 12:35 UTC, miguel567 commented on content/es/learn/module-0/money-language.mdx
> +> "Piensa en la frecuencia con la que se ha transformado la tecnología del dinero. Básicamente, la comunicación de valor puede tener lugar a través de un intercambio de cosas de igual valor. La prime
AS-IS: "Luego nada durante unos miles de años. Luego vino la idea de que puedo depositar mi oro con alguien de confianza, que puede emitir un certificado en papel para mi depósito, y puedo comerciar con ese papel."

TO-BE: "Luego nada ocurrió durante unos miles de años. Posteriormente, vino la idea de que puedo depositar mi oro con alguien de confianza, que puede emitir un certificado en papel para mi depósito, y puedo comerciar con ese papel."

2022-04-07 12:35 UTC, miguel567 commented on content/es/learn/module-0/money-language.mdx
> +> "El dinero 'par-a-par' se refiere a una arquitectura que describe la relación entre los participantes en un sistema (distribuido). La arquitectura de Bitcoin es par-a-par porque **cada participante
AS-IS: "El dinero 'par-a-par' se refiere a una arquitectura que describe la relación entre los participantes en un sistema (distribuido). La arquitectura de Bitcoin es par-a-par porque **cada participante en la red habla el protocolo Bitcoin al mismo nivel**."

I'm thinking "de-igual-a-igual" is easier to understand in spanish.

TO-BE: "El dinero 'de-igual-a-igual' se refiere a una arquitectura que describe la relación entre los participantes en un sistema (distribuido). La arquitectura de Bitcoin es de-igual-a-igual porque **cada participante en la red habla el protocolo Bitcoin al mismo nivel**."

2022-04-07 12:35 UTC, miguel567 commented on content/es/learn/module-0/money-language.mdx
> +### Maestro-esclavo vs par-a-par
AS-IS: ### Maestro-esclavo vs par-a-par

TO-BE: ### Maestro-esclavo vs de-igual-a-igual

2022-04-07 12:35 UTC, miguel567 commented on content/es/learn/module-0/money-language.mdx
> +> "Otro término que se usa para esta arquitectura cliente-servidor en la que solo mantiene una copia débil es una arquitectura **maestro-esclavo**. Si piensa en las tecnologías de dinero anteriores q
AS-IS; "Otro término que se usa para esta arquitectura cliente-servidor en la que solo mantiene una copia débil es una arquitectura **maestro-esclavo**. Si piensa en las tecnologías de dinero anteriores que usan esta arquitectura maestro-esclavo, debe preguntarle a un pregunta incómoda: ¿quién es el esclavo?"

TO-BE: "Otro término que se usa para esta arquitectura cliente-servidor en la que solo mantiene una copia débil es una arquitectura **maestro-esclavo**. Si piensa en las tecnologías de dinero anteriores que usan esta arquitectura maestro-esclavo, debe preguntarse una pregunta incómoda: ¿Quién es el esclavo?"

2022-04-07 12:35 UTC, miguel567 commented on content/es/learn/module-0/money-language.mdx
> +R: Par-a-par.
AS-IS: "R: Par-a-par."

To-BE: "R: De-igual-a-igual."

2022-04-07 12:35 UTC, miguel567 commented on content/es/learn/module-0/money-language.mdx
> +Más adelante, en la sesión de preguntas y respuestas, Andreas señala que "Bitcoin es una opción, es una elección". Entonces, el Internet del dinero no es un hecho: es lo que estamos construyendo ahor
AS-IS: "Más adelante, en la sesión de preguntas y respuestas, Andreas señala que "Bitcoin es una opción, es una elección". Entonces, el Internet del dinero no es un hecho: es lo que estamos construyendo ahora. Es nuestra responsabilidad hacerlo transparente y eminentemente usable, mientras lo mantenemos entre pares, sin fronteras, abierto y justo."

TO-BE. "Más adelante, en la sesión de preguntas y respuestas, Andreas señala que "Bitcoin es una opción, es una elección". Entonces, el Internet del dinero no es un hecho: es lo que estamos construyendo ahora. Es nuestra responsabilidad hacerlo transparente y eminentemente usable, mientras lo mantenemos entre iguales, sin fronteras, abierto y justo."

2022-04-07 13:49 UTC, gjacuna commented on content/es/learn/module-0/conversation.mdx
> +¿Qué tipos de **discurso** realmente tiene **valor**?
¿Qué tipo de **discurso** realmente tiene **valor**?
(Took the s from tipos away)

2022-04-07 13:49 UTC, gjacuna commented on content/es/learn/module-0/conversation.mdx
> +Este documental presenta a Paul Myburgh, autor de *El Invierno De Los Bosquimanos Ha Llegado*, quien pasó siete años viviendo con los bosquimanos !Gwi Kalahari Bosquimanos, explorando la conversación
as is: pasó siete años viviendo con los bosquimanos !Gwi Kalahari Bosquimanos
to be: pasó siete años viviendo con los Bosquimanos !Gwi Kalahari

2022-04-07 13:49 UTC, gjacuna commented on content/es/learn/module-0/conversation.mdx
> +¿Qué cómodo te sientes con el silencio? ¿No es esta realmente la medida del compañerismo? ¿Qué cómodos son los silencios?
as is: Qué cómodo
to be: Qué tan cómodo
(both questions have to changed)

2022-04-07 13:49 UTC, gjacuna commented on content/es/learn/module-0/conversation.mdx
> +> "La humanidad moderna no aprende siendo dotada. Nuestro camino es otro. Estamos constituidos para hacer preguntas. Para nosotros, conocer es algo que se logra con esfuerzo, con libre albedrío. La t
"Un largo y tortuoso camino" quizás?

2022-04-07 13:49 UTC, gjacuna commented on content/es/learn/module-0/conversation.mdx
> +> "Cada vez más veo el valor en conversaciones humanas: el valor de lo que surge entre nosotros cuando hablamos en verdad con lo que tenemos y lo que buscamos. Todos nosotros. Cuando veo esta convers
as is: **encontrar lo que fue la antigua comunidad en forma futura**
I'm not entirely comfortable with this wording. maybe this is better?
to be: **encontrar las antiguas forma de comunidad en sus formas futuras**

2022-04-07 13:49 UTC, gjacuna commented on content/es/learn/module-0/money-language.mdx
> +> "Si piensas en el dinero como tecnología, ¿qué edad tiene esta tecnología? \[...\] Siempre es sorprendente que la gente diga: 'Oh, 400 años', '1000 años', 'unos miles de años viejo". De hecho, no s
as is: 'unos miles de años viejo"
to be: 'unos miles de años de antigüedad'"
as is: Todavía tenemos que descubrir una civilización que no tuviera dinero
to be: Aún no hemos descubierto una civilización sin dinero

2022-04-07 13:49 UTC, gjacuna commented on content/es/learn/module-0/money-language.mdx
> +Una vez que agregamos la capacidad de programar este medio utilizando un script completo de Turing, deberíamos comenzar a pensar en todo esto no en términos de un nuevo lenguaje, sino como un *desarr
as is: programar este medio utilizando un script completo de Turing
to be: programa este medio usando un lenguaje Turing completo
(as per wikipedia: https://es.wikipedia.org/wiki/Turing_completo)

2022-04-07 13:49 UTC, gjacuna commented on content/es/learn/module-0/money-language.mdx
> +Realmente estamos viendo un cambio de fase en el poder expresivo del dinero: es decir, ahora se puede programar para *hacer cosas dinámicamente* además de ser comerciado. ¿Por qué importa que ahora t
I'm having doubts about the phrase "centrada en la red". I like "sobre la red" better, but I'm not very convinced, haha

2022-04-07 13:49 UTC, gjacuna commented on content/es/learn/module-0/money-language.mdx
> +P: Bitcoin transforma la tecnología del dinero en un protocolo centrado en la red. Como tal, no es un nuevo tipo de lenguaje, sino un desarrollo del \_\_\_\_\_ del lenguaje.
There's an extra "del" in "del lenguaje"

2022-04-07 13:49 UTC, gjacuna commented on content/es/learn/module-0/money-language.mdx
> +> "El dinero 'par-a-par' se refiere a una arquitectura que describe la relación entre los participantes en un sistema (distribuido). La arquitectura de Bitcoin es par-a-par porque **cada participante
I'd just leave peer-to-peer. It's a term most people will understand.

2022-04-09 18:50 UTC, fangningc commented on content/es/learn/module-0/conversation.mdx
> +> "La humanidad moderna no aprende siendo dotada. Nuestro camino es otro. Estamos constituidos para hacer preguntas. Para nosotros, conocer es algo que se logra con esfuerzo, con libre albedrío. La t
I went for "Un largo camino"

2022-04-09 18:54 UTC, fangningc commented on content/es/learn/module-0/money-language.mdx
> +> "El dinero 'par-a-par' se refiere a una arquitectura que describe la relación entre los participantes en un sistema (distribuido). La arquitectura de Bitcoin es par-a-par porque **cada participante
Hi both, in the previous reading, we decided on "par a par" (row 16 https://docs.google.com/spreadsheets/d/1RGbR4UtTaY3QkaIus4ri89nUpssXg02_qtF08Ufipow/edit#gid=0), so in the name of consistency, I will leave it as is for now. If we really don't like it, we can do a sweep and change it to "peer-to-peer", I think there are other nuances, since there are reference to a single peer, so how should be translated or not.

2022-04-09 18:58 UTC, fangningc commented on content/es/learn/module-0/money-language.mdx
> +> "Otro término que se usa para esta arquitectura cliente-servidor en la que solo mantiene una copia débil es una arquitectura **maestro-esclavo**. Si piensa en las tecnologías de dinero anteriores q
nice catch, instead of using third person, I have been using second throughout the syllabus, that is "tu" instead of "usted", therefore I changed it to "debes preguntarte".

2022-04-09 19:33 UTC, fangningc commented on content/es/learn/module-0/money-language.mdx
> +P: Bitcoin transforma la tecnología del dinero en un protocolo centrado en la red. Como tal, no es un nuevo tipo de lenguaje, sino un desarrollo del \_\_\_\_\_ del lenguaje.
Como tal, no es un tipo de lenguage, sino un desarrollo del **orden** del lenguage. 

"Orden" would replace the "\_\_\_\_\_" so, I think it necessary amount of "del"s :)

2022-05-24 07:37 UTC, merged